//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomAppMusicBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.Singers = new HashSet<Singers>();
        }
    
        public int idContract { get; set; }
        public string NameContract { get; set; }
        public string MusicStudio { get; set; }
        public string NameSinger { get; set; }
        public string FamiliaSinger { get; set; }
        public string PatronymicSinger { get; set; }
        public string NameProducer { get; set; }
        public Nullable<System.DateTime> YearBirthday { get; set; }
        public Nullable<int> CountCompositons { get; set; }
        public string Experience { get; set; }
        public Nullable<System.DateTime> DataStart { get; set; }
        public Nullable<System.DateTime> DataEnd { get; set; }
        public Nullable<decimal> Profit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Singers> Singers { get; set; }
    }
}
