//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomAppMusicBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tirage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tirage()
        {
            this.Singers = new HashSet<Singers>();
        }
    
        public int idTirage { get; set; }
        public string NameTirage { get; set; }
        public string NameSinger { get; set; }
        public string FamiliaSinger { get; set; }
        public string PatronymicSinger { get; set; }
        public string NameAlbom { get; set; }
        public Nullable<int> CountAlboms { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string FormattedPrice
        {
            get
            {
                return string.Format("{0} ₽", Price);
            }
        }
        public string City { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public string FormattedProfit
        {
            get
            {
                return string.Format("{0} ₽", Profit);
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Singers> Singers { get; set; }
    }
}
